### ISSUE TITLE
Add debug logging for trigger binding support

### ISSUE THREAD

**Issue by JatinSanghvi** [Azure/azure-functions-sql-extension#287]
_Originally posted by @Charles-Gagnon in https://github.com/Azure/azure-functions-sql-extension/pull/226#pullrequestreview-1056074438_

Although I want there to be a lot more debug logging done in all the parts. I'm not seeing any in SqlTableChangeMonitor for example. In general here are the things I'll be looking for : 

- [x] 1. Message at the start of every task and sub task (`Getting changes from table`, `Updating state tables`, `Getting list of changes`, `Got changed rows {....}`) and so on. The goal should be to be able to tell exactly where something went wrong and what it was doing when an issue occurs, regardless of where that was.  _**(addressed by #289)**_
- [x] 2. Log queries executed and how long they took _**(addressed by #289)**_
- [ ] ~~3. Extra logging around any of the locking (include thread IDs if that isn't included by default)~~ (moved to #321)
- [x] 4. Make sure all errors are logged with any extra information that may be helpful in determining cause of the error _**(addressed by #289)**_
- [x] Also we should make sure to get basic usage telemetry set up - we can get some amount of stuff from the AF folks but that won't include people running locally so it'd be good to make sure we have a complete story ourselves as well. I'll follow up separately on my thoughts for that to get started. _**(addressed by #289)**_

**Comment by JatinSanghvi** [comment]
#289 addresses most of points 1, 2, 4 and the telemetry suggestion.

**Comment by chlafreniere** [comment]
@JatinSanghvi can we prioritize this issue re: logging for locking in general? This will really help when it comes to being able to diagnose customer issues from logs.

**Comment by Charles-Gagnon** [comment]
@JatinSanghvi 

Some more things that should be added as well : 

1. More coverage of all subtasks. Especially when we're doing SQL queries - we should have logging statements before and after each query ran. 

e.g. https://github.com/Azure/azure-functions-sql-extension/blob/triggerbindings/src/TriggerBinding/SqlTriggerListener.cs#L189 and https://github.com/Azure/azure-functions-sql-extension/blob/triggerbindings/src/TriggerBinding/SqlTableChangeMonitor.cs#L195

2. Logging for each iteration of a loop and before each sleep (e.g. https://github.com/Azure/azure-functions-sql-extension/blob/triggerbindings/src/TriggerBinding/SqlTableChangeMonitor.cs#L159)

**Comment by JatinSanghvi** [comment]
I did not get much time to work on the comments. I will work on them before picking any new tasks. Created #321 to have a focused GitHub issue tracking the to-do items around comments and give closure to the completed work.
