### ISSUE TITLE
SQL trigger firing from stage slot when it should be disabled

### ISSUE THREAD

**Issue by grantpalmer-carvana** [Azure/azure-functions-sql-extension#882]
We are running into some issues where the SQL table trigger is occasionally firing from the stage slot while swapping slots during a release. We have slot settings in place to disable the sql trigger function unless it is the prod slot. 

For these logs, the values used are:
``` 
var hostName = Environment.GetEnvironmentVariable("WEBSITE_SITE_NAME");
var slotName = Environment.GetEnvironmentVariable("WEBSITE_SLOT_NAME");
var slotSettingValue = Environment.GetEnvironmentVariable("AzureWebJobs.CheckoutRequestTrigger.Disabled");
```

We had a branch deployed to test that had logging that didn't include the slot setting value as can be seen by the trace from 12:06. While swapping slots at 12:09:27, the sql trigger fired from the stage slot, had a function disabled slot setting value of false which corresponds to the expected value for the prod slot, and had msi/hostname corresponding to the prod slot of the function app.  The app insights telemetry role name for that trace is that of the stage-slot. 

The trace from 12:10:05 shows a log running off of the previous iteration of the code since it doesn't contain the slot setting portion of the log. The app insights telemetry role name for this trace is that of the prod-slot. It also would've needed the prod-slot disabled slot setting to be false in order for this log to be created. 

Taking all of this into account, it appears as if the sql trigger is currently able to fire from the stage slot while doing a slot swap during a release despite there being a slot setting to disable the sql trigger function for stage. When it does so, it uses the prod slot msi/hostname and app settings although it is in the stage-slot. When this occurs, an app lease table is created for the stage slot as well. Following the completion of performing the slot swap, the stage-slot function is disabled and does not continue to trigger from changes to the sql table that it tracks so this is only seen when performing a slot swap.

![image (1)](https://github.com/Azure/azure-functions-sql-extension/assets/131677375/29638ed2-f0d3-45f3-b1a4-3c0da3dc391d)

```[tasklist]
### Tasks
- [x] Add optional LeaseTableNameSetting to SqlTriggerAttribute
- [x] Release new extension
- [x] Release new worker extension
- [x] Release new preview extension bundle
- [x] Release new java library
- [x] Update python sql decorator
- [x] Update docs
```

**Comment by lucyzhang929** [comment]
Hello @grantpalmer-carvana, based on these [docs](https://learn.microsoft.com/en-us/azure/azure-functions/functions-deployment-slots#swap-operations) it seems like production settings being applied to staging slot during a swap is expected behavior. "Settings from the target slot are applied to all instances of the source slot. For example, the production settings are applied to the staging instance."

You can mark the "AzureWebJobs.CheckoutRequestTrigger.Disabled" app setting as a [Deployment setting](https://learn.microsoft.com/en-us/azure/azure-functions/functions-deployment-slots#create-a-deployment-setting) so that it does not get swapped.

Please let me know if this does not work or if I am misunderstanding the issue!

**Comment by grantpalmer-carvana** [comment]
In this scenario, the AzureWebJobs.CheckoutRequestTrigger.Disabled app setting is a deployment setting and still appears to be getting swapped during this execution since it is set as true for the stage-slot. We believe it may be due to the deployment pipeline structure that we are using for this repo where the swap is occurring immediately after applying the slot settings. We are going to set up another more targeted repo/pipeline to try to reproduce the issue and get a better idea of what is occurring in these cases.

**Comment by bcrispcvna** [comment]
After more research, a more accurate description of the problem is that during a slot swap, the code being swapped into the production slot is executing the sqltrigger before the WEBSITE_SLOT_NAME environment variable is updated.  This causes the [GetUserFunctionIdAsync method in the SqlTriggerBinding](https://github.com/Azure/azure-functions-sql-extension/blob/f3eafb01c092036bad3d1e557af2dc117640d91d/src/TriggerBinding/SqlTriggerBinding.cs#L98C36-L98C58) to return a value based on the stage slot.  This causes a second lease table and entry in the global state, and duplicate executions of the sql trigger once the value is updated properly. 
![image](https://github.com/Azure/azure-functions-sql-extension/assets/133140387/7c0d8737-85ec-4fbd-a4ba-46a79681cc51)

Interestingly enough, it doesn't happen every time, so it could be that sometimes the slot name is updated before the binding is set up.

I reproduced the issue in a fresh function project with only 1 SqlTrigger, so it's not limited to our deployment process.

To reproduce the issue, I followed these steps:
- set up an azure sql db and enable change tracking
- create a function app with a function using using Microsoft.Azure.WebJobs.Extensions.Sql 3.0.253-preview

```
using System.Net.Http.Headers;
using System.Text.Json;
using System.IdentityModel.Tokens.Jwt;
using Azure.Core;
using Azure.Identity;
using Microsoft.Azure.WebJobs.Extensions.Sql;

namespace SwapFunction;

public partial class SwapTestTrigger
{
    private const string PostSaleDbConnectionStringSettingName = "DbConnectionString";
    private readonly ILogger<SwapTestTrigger> _logger;

    public SwapTestTrigger(
        ILogger<SwapTestTrigger> logger)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    [FunctionName(nameof(SwapTestTrigger))]
    public async Task Run(
        [SqlTrigger("[dbo].[ChangeRequests]", PostSaleDbConnectionStringSettingName)]
            IReadOnlyList<SqlChange<ChangeRequest>> changes)
    {
        var msiName = await GetManagedServiceIdentityName();

        var hostName = Environment.GetEnvironmentVariable("WEBSITE_SITE_NAME");
        var slotName = Environment.GetEnvironmentVariable("WEBSITE_SLOT_NAME");
        var slotSettingValue = Environment.GetEnvironmentVariable("AzureWebJobs.SwapTestTrigger.Disabled");

        _logger.LogInformation(new EventId(900, "SwapTestTrigger"), 
            "SwapTestTrigger executed with Msi: {MsiName} with host name {HostName} on slot: {SlotName} with slot setting value AzureWebJobs.SwapTestTrigger.Disabled: {SlotSettingValue}",
            msiName, hostName, slotName, slotSettingValue);
    }

    public static async Task<string> GetManagedServiceIdentityName()
    {
        const string graphResource = "https://graph.microsoft.com/";

        if (string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable("IDENTITY_HEADER"))) return string.Empty;

        var p = new DefaultAzureCredential();
        var accessToken = await p.GetTokenAsync(new TokenRequestContext(new[] { graphResource }));

        var jwtToken = new JwtSecurityToken(accessToken.Token);
        var objectId = jwtToken.Claims.FirstOrDefault(c => c.Type == "oid")?.Value;

        using var httpClient = new HttpClient();
        httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken.Token);

        var response = await httpClient.GetAsync($"{graphResource}v1.0/servicePrincipals/{objectId}");
        response.EnsureSuccessStatusCode();

        var jsonResponse = await response.Content.ReadAsStringAsync();
        var responseObject = JsonDocument.Parse(jsonResponse);

        return responseObject.RootElement.GetProperty("displayName").GetString() ?? string.Empty;
    }    
}
```

- add a sticky slot setting for disabling the function on the stage slot "AzureWebJobs.SwapTestTrigger.Disabled" : "true"
- publish and deploy the function app to the stage slot (we are using run from package).
- insert a new row into the table that's being tracked
- perform a slot swap (repeat these last two steps several times as needed)
- check after each swap whether a second lease table is created and if a 2nd entry in the GlobalState is added.  

here's what I would see in app insights where it logs the executions with the stage-slot environment variable.
![image](https://github.com/Azure/azure-functions-sql-extension/assets/133140387/aea39f85-0ba6-452f-ae2a-4a1e64ceb926)

As a workaround we are now checking the WEBSITE_SLOT_NAME environment variable on trigger execution and throwing an exception if it's not executed in the Production slot.  This doesn't prevent the 2nd lease table from being created, but it is preventing the duplicate execution that we were seeing.

**Comment by bcrispcvna** [comment]
I should also add that the above was done using a windows host.  out of curiosity I tried it on linux, and after the swap, the WEBSITE_SLOT_NAME remained as stage-slot, and it executed as expected with multiple triggers from inserts... until I restarted the app.  At this time the second lease table was created.  But instead of it just executing as Production, each change would trigger twice for each website_slot_name, even though the code is only running in the prod slot.  
![image](https://github.com/Azure/azure-functions-sql-extension/assets/133140387/771e090a-00f8-4314-b445-96bb208cd549)

**Comment by bcrispcvna** [comment]
@lucyzhang929 I think we're talking two separate issues here.  The trigger is not firing from the stage slot as the title of this issue stated.  It just appears that way in logs because the WEBSITE_SLOT_NAME environment variable isn't changing during the swap.  That's also why in the reproduction I only had code deployed to one slot.  It is specific to sql bindings in that it's using a non-deterministic value in the hash for UserFunctionId, and creates two desynced lease tables even without slot specific settings.  Do you want me to open a new ticket specifically around the host name/UserFunctionId issue?  I can narrow the focus specifically around how every scenario where slots are involved results in incorrect behavior.  We need a truly deterministic UserFunctionId for SqlTrigger to function as expected.   We don't see an issue like this with cosmos because the LeaseCollectionName and Prefix are defined in the trigger attributes.  I would expect SqlTrigger to ideally have the same behavior.

**Comment by lucyzhang929** [comment]
@bcrispcvna Thank you for clarifying. I've reopened the issue and will continue to investigate.

**Comment by lucyzhang929** [comment]
@grantpalmer-carvana @bcrispcvna We released a new version of the sql extension with an optional 'LeasesTableName' property added to the SqlTriggerAttribute.
