### ISSUE TITLE
Merge trigger branch and update docs/links in code to remove reference to trigger branch

### ISSUE THREAD

**Issue by lucyzhang929** [Azure/azure-functions-sql-extension#894]
(after merging trigger branch into main)
```[tasklist]
### Tasks
- [x] Merge release/trigger branch too main
- [x] Update all the trigger docs/links correctly.
- [x] Update the public docs which are pointing to release/trigger branch
- [x] Remove Preview from docs and update host.json & templates to point to ExtensionBundle.
- [x] Update docs that SQL Bindings is part of Extension bundle once we update the templates.
```

**Comment by MaddyDev** [comment]
Updated templates (https://github.com/Azure/azure-functions-templates/pull/1456 and https://github.com/Azure/azure-functions-templates/pull/1451).
Updated Extension bundle (https://github.com/Azure/azure-functions-extension-bundles/pull/299)
